/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.InHomePatient.InHomePatient;
import Business.Network.Network;
import Business.WorkQueue.DoctorByHospitalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harika
 */
public class RequestForDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestForDoctorJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private InHomePatient inHomePatient;
    private EcoSystem system;
    private Enterprise.EnterpriseType type;
    
    public RequestForDoctorJPanel(JPanel userProcessContainer, Enterprise enterprise, Network network, InHomePatient inHomePatient, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.inHomePatient = inHomePatient;
        this.system=system;
        this.type=type;
        populateRequestTable();
        jDateChooser1.getJCalendar().setMinSelectableDate(new Date());
        
        
    }

    

    public void populateRequestTable() {
        //System.out.println("Testing123");
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        
        for (WorkRequest request : system.getWorkQueue().getWorkRequestList()) {
            if(request.getInhomepatient()!=null){
//                System.out.println(request);
//                System.out.println(inHomePatient);
//                System.out.println(request.getInhomepatient());
//                System.out.println(enterprise.getEnterpriseType().getValue());
//                System.out.println(request.getEnterprise().getEnterpriseType().getValue());
            if (request instanceof DoctorByHospitalWorkRequest && request.getInhomepatient().getPatientName().equalsIgnoreCase(inHomePatient.getPatientName())  && request.getEnterprise().getEnterpriseType().getValue()==enterprise.getEnterpriseType().getValue() && network.getName().equalsIgnoreCase(request.getCity())) {
                Object[] row = new Object[6];
                row[0] = ((DoctorByHospitalWorkRequest) request);
                row[1] = ((DoctorByHospitalWorkRequest) request).getRequestingDate();
                row[2] = ((DoctorByHospitalWorkRequest) request).getRequestDate();
                row[3] = ((DoctorByHospitalWorkRequest) request).getResolveDate();
                row[4] = ((DoctorByHospitalWorkRequest) request).getStatus();
                row[5] = ((DoctorByHospitalWorkRequest) request).getMessage();
                /* String result = ((StaffWorkRequest) request).getTestResult();
                 row[3] = result == null ? "Waiting" : result;
                 */
                model.addRow(row);
            }
            }
    }}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CommentsTextField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(null);

        enterpriseLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel1.setText("Request for Doctors");
        add(enterpriseLabel1);
        enterpriseLabel1.setBounds(540, 30, 580, 80);

        workRequestJTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        workRequestJTable.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Physician Name", "Request Appointment Day", "Requested Date", "Accepted Date", "Status", "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 410, 1200, 190);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Request Appointment Day* : ");
        add(jLabel2);
        jLabel2.setBounds(370, 630, 240, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Medical Aid required for :");
        add(jLabel3);
        jLabel3.setBounds(370, 680, 230, 17);

        CommentsTextField.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        CommentsTextField.setForeground(new java.awt.Color(0, 102, 102));
        CommentsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentsTextFieldActionPerformed(evt);
            }
        });
        add(CommentsTextField);
        CommentsTextField.setBounds(640, 670, 150, 30);

        backBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Back.PNG"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(12, 13, 62, 60);

        SubmitButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(0, 102, 102));
        SubmitButton.setText("Submit Request");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        add(SubmitButton);
        SubmitButton.setBounds(440, 730, 170, 29);

        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 102, 102));
        btnCancel.setText("Cancel Request");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        add(btnCancel);
        btnCancel.setBounds(440, 780, 171, 29);

        jDateChooser1.setForeground(new java.awt.Color(0, 102, 102));
        add(jDateChooser1);
        jDateChooser1.setBounds(640, 630, 150, 26);

        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Doctorslogin.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1600, 1200);
    }// </editor-fold>//GEN-END:initComponents

    private void CommentsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommentsTextFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        //Date reqDate = RequestingDateTextField.getDate();
        Date reqDate=jDateChooser1.getDate();
        String mess = CommentsTextField.getText();
        if (reqDate == null) {

            JOptionPane.showMessageDialog(null, "Date cannot be empty");
        } else {
            DoctorByHospitalWorkRequest request = new DoctorByHospitalWorkRequest();
            
            request.setRequestingDate(reqDate);
            request.setdoctorName(null);
            request.setInhomepatient(inHomePatient);
            request.setRequestDate(new Date());
            request.setResolveDate(null);
            request.setStatus("Requested");
            request.setMessage(mess);
            request.setEnterprise(enterprise);
            request.setActiveLead("Doctor");
            request.setCity(network.getName());
            

//            Enterprise ent = null;
//            for (Network network1:system.getNetworkList()){
//                
//                if(network1==network){
//                for (Enterprise enterprise : network1.getEnterpriseDirectory().getEnterpriseList()) {
//                    if (enterprise instanceof HospitalEnterprise ) {
//                        ent = enterprise;
//                        break;
//                    }
//                }
//            if (ent != null) {
            system.getWorkQueue().getWorkRequestList().add(request);
            System.out.println(request);
            populateRequestTable();
            //System.out.println(userAccount.getWorkQueue().getWorkRequestList().get(0).toString());
            //System.out.println(userAccount.getWorkQueue().getWorkRequestList().get(1).toString());

        }
            
        //RequestingDateTextField.setDate(null);
           CommentsTextField.setText("");
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int row = workRequestJTable.getSelectedRow();
        if(row>=0){
        WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(row,0);
        system.getWorkQueue().getWorkRequestList().remove(request);
        populateRequestTable();
        }
        else if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CommentsTextField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel enterpriseLabel1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
