/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.InHomePatient.InHomePatient;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import userinterface.Patient.NewPatientLoginJPanel;
import userinterface.PatientRole.PatientWorkAreaPanel;

/**
 *
 * @author Mounica Dantuluri
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
//        system.getWorkQueue().getWorkRequestList().clear();
//        system.getInHomePatientDirectory().getPatientList().clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btnAboutUs = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnEmergency = new javax.swing.JButton();
        Container = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eMailTxtField = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        passwordTxtField = new javax.swing.JPasswordField();
        btnPatient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        btnAboutUs.setBackground(new java.awt.Color(0, 102, 102));
        btnAboutUs.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAboutUs.setForeground(new java.awt.Color(0, 102, 102));
        btnAboutUs.setText("About Us");
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 102, 102));
        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 102, 102));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnEmergency.setBackground(new java.awt.Color(0, 102, 102));
        btnEmergency.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnEmergency.setForeground(new java.awt.Color(0, 102, 102));
        btnEmergency.setText("Emergency");
        btnEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmergencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEmergency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(btnAboutUs)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(18, 18, 18)
                .addComponent(btnEmergency)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel2);

        Container.setBackground(new java.awt.Color(0, 102, 102));
        Container.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 330, 120, 21);

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 380, 120, 21);

        eMailTxtField.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(eMailTxtField);
        eMailTxtField.setBounds(210, 320, 230, 40);

        btnLogin.setBackground(new java.awt.Color(0, 102, 102));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 102, 102));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(60, 440, 230, 40);

        passwordTxtField.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(passwordTxtField);
        passwordTxtField.setBounds(210, 370, 230, 40);

        btnPatient.setBackground(new java.awt.Color(0, 102, 102));
        btnPatient.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnPatient.setForeground(new java.awt.Color(0, 102, 102));
        btnPatient.setText("Patient SignUp");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        jPanel1.add(btnPatient);
        btnPatient.setBounds(60, 500, 230, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel2.setText("Happy Health Services");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 520, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Page1 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1530, 1000);

        Container.add(jPanel1, "card2");

        jSplitPane2.setRightComponent(Container);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutUsActionPerformed
//         TODO add your handling code here:
                            
                         JOptionPane.showMessageDialog(null, "When You Want the BEST in Home Health Care\n\n" + "We are here to serve you\n" +
"\n" +
" Experts Guide and Care when you need it most\n" +
" We know how to navigate healthcare challenges.\n" +
"Hands-on-Help\n\n" +
" Care Management: We can help you navigate the complex medical, legal and financial landscape. We help with day-to-day care too, including coordination of doctor visits, medications, dietary needs and more.\n" +

" Hourly/Live-in Home Care: Whether you need care for a few hours, or around the clock, our closely-screened caregivers can help with daily living activities such as meal prep, housekeeping, personal care and bathing.\n" +

" Private Duty Nursing: Our highly-qualified nurses can quickly adapt to changing medical needs, providing the specialized assistance you need.\n" +
" Specialty Companion Care: Our team of Companions can provide regular social interaction, accompaniment to social events, assistance with shopping, and help with favorite hobbies and activities.\n" +
"depending upon the vaccination availability as per the recent mortality rates\n" +
" Find Services Near You\n"+
" We are proud to offer professional care services in many countries across the Globe. Our network of branches includes integrated teams of care professionals, so we can provide continuity of care and seamless transfer of medical records when you travel or move."                              );
    }//GEN-LAST:event_btnAboutUsActionPerformed

    private void btnEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergencyActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "In Emergency Contact us at +1 857 800 6589\n"+"Email:happy_health@healthservices.com");
    }//GEN-LAST:event_btnEmergencyActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        btnLogout.setEnabled(false);
        eMailTxtField.setEnabled(true);
        passwordTxtField.setEnabled(true);
        btnLogin.setEnabled(true);

        eMailTxtField.setText("");
        passwordTxtField.setText("");

        Container.removeAll();
        //JPanel blankJP = new JPanel();
        Container.add("blank", jPanel1);
        CardLayout crdLyt = (CardLayout) Container.getLayout();
        crdLyt.next(Container);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:

        CardLayout layout=(CardLayout)Container.getLayout();
        NewPatientLoginJPanel newPatientLoginJPanel = new NewPatientLoginJPanel(Container, system);
        Container.add("newpatientlogin",newPatientLoginJPanel);
        layout.next(Container);
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        // Get user name
        String userName = eMailTxtField.getText();
        // Get Password
        char[] passwordCharArray = passwordTxtField.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the admin user account directory if you have the user
        UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);

        Enterprise inEnterprise=null;
        Organization inOrganization=null;
        Network inNetwork = null;

        if(userAccount==null){

            //Step 2: Go inside each network and check each enterprise
            for(Network network:system.getNetworkList()){
                //Step 2.a: check against each enterprise
                //inNetwork = network;
                for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                    userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);

                    //System.out.println(network);
                    //inNetwork = network;
                    //System.out.println(enterprise.getEnterpriseType().getValue());
                    if(userAccount==null){
                        //Step 3:check against each organization for each enterprise
                        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                            userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if(userAccount!=null){
                                inEnterprise=enterprise;
                                inOrganization=organization;
                                inNetwork=network;
                                break;
                            }
                        }

                    }
                    else{
                        inEnterprise=enterprise;
                        //System.out.println(network);
                        inNetwork = network;
                        break;
                    }
                    if(inOrganization!=null){
                        break;
                    }
                }
                if(inEnterprise!=null){
                    break;
                }
                /*if(inNetwork!=null){
                    break;
                }*/
                //inNetwork = network;
            }
        }
        if(userAccount==null){
            InHomePatient inHomePatient=system.getInHomePatientDirectory().authenticateUser(userName, password);
            System.out.println(inHomePatient);
            System.out.println(system.getInHomePatientDirectory().getPatientList());
            if(inHomePatient!=null){
                CardLayout layout=(CardLayout)Container.getLayout();
                PatientWorkAreaPanel patientWorkAreaPanel = new PatientWorkAreaPanel(Container, inHomePatient, system);
                Container.add("PatientWorkAreaPanel", patientWorkAreaPanel);
                layout.next(Container);
            }
            else if(userAccount==null){
                JOptionPane.showMessageDialog(null, "Invalid credentials");
                return;

            }
        }
        else{
            CardLayout layout=(CardLayout)Container.getLayout();
            Container.add("workArea",userAccount.getRole().createWorkArea(Container, userAccount, inOrganization, inEnterprise, inNetwork, system));
            layout.next(Container);
        }

        btnLogin.setEnabled(false);
        btnLogout.setEnabled(true);
        eMailTxtField.setEnabled(false);
        passwordTxtField.setEnabled(false);
    }//GEN-LAST:event_btnLoginActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnEmergency;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPatient;
    private javax.swing.JTextField eMailTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPasswordField passwordTxtField;
    // End of variables declaration//GEN-END:variables
}
