/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManageEnterpriseAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ikyathvarmadantuluri
 */
public class HospitalViewServicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalViewServicesJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private UserAccount userAccount;
    private EcoSystem ecosystem;

    HospitalViewServicesJPanel(JPanel userProcessContainer, Enterprise enterprise, Network network, UserAccount userAccount, EcoSystem ecosystem) {
        initComponents();
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        this.userProcessContainer=userProcessContainer;
        this.network=network;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewStaffRequests = new javax.swing.JButton();
        btnViewHospitalRequests = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(null);

        btnViewStaffRequests.setBackground(new java.awt.Color(0, 102, 102));
        btnViewStaffRequests.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnViewStaffRequests.setForeground(new java.awt.Color(0, 102, 102));
        btnViewStaffRequests.setText("View Staff Requests");
        btnViewStaffRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStaffRequestsActionPerformed(evt);
            }
        });
        add(btnViewStaffRequests);
        btnViewStaffRequests.setBounds(185, 190, 293, 98);

        btnViewHospitalRequests.setBackground(new java.awt.Color(0, 102, 102));
        btnViewHospitalRequests.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnViewHospitalRequests.setForeground(new java.awt.Color(0, 102, 102));
        btnViewHospitalRequests.setText("View Requests for Doctors");
        btnViewHospitalRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospitalRequestsActionPerformed(evt);
            }
        });
        add(btnViewHospitalRequests);
        btnViewHospitalRequests.setBounds(185, 340, 293, 98);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Back.PNG"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(12, 13, 70, 61);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Health Services.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1600, 1200);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewStaffRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStaffRequestsActionPerformed
        // TODO add your handling code here:
        ViewStaffRequestsJPanel viewStaffRequestsJPanel = new ViewStaffRequestsJPanel( userProcessContainer,  enterprise,  network, userAccount, ecosystem);
        userProcessContainer.add("viewStaffRequestsJPanel", viewStaffRequestsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewStaffRequestsActionPerformed

    private void btnViewHospitalRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospitalRequestsActionPerformed
        // TODO add your handling code here:
        ViewPatientRequestsJPanel viewPatientRequestsJPanel = new ViewPatientRequestsJPanel( userProcessContainer,  enterprise,  network, userAccount, ecosystem);
        userProcessContainer.add("ViewPatientRequestsJPanel", viewPatientRequestsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewHospitalRequestsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewHospitalRequests;
    private javax.swing.JButton btnViewStaffRequests;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
