/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManageEnterpriseAdmin;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harika
 */
public class PharmacyRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyRequestJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private UserAccount userAccount;
    public PharmacyRequestJPanel(JPanel userProcessContainer, Enterprise enterprise, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.userAccount = userAccount;
        populateRequestTable();
        initComponents();
    }
    
    public void populateRequestTable() {
        //System.out.println("Testing123");
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            if (request instanceof PharmacyWorkRequest) {
                Object[] row = new Object[7];
                row[0] = ((PharmacyWorkRequest) request);
                row[1] = ((PharmacyWorkRequest) request).getDrugQuantity();
                row[2] = ((PharmacyWorkRequest) request).getSender();
                row[3] = ((PharmacyWorkRequest) request).getReceiver();
                row[4] = ((PharmacyWorkRequest) request).getRequestDate();
                row[5] = ((PharmacyWorkRequest) request).getResolveDate();
                row[6] = ((PharmacyWorkRequest) request).getStatus();
                /* String result = ((StaffWorkRequest) request).getTestResult();
                 row[3] = result == null ? "Waiting" : result;
                 */
                model.addRow(row);
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        SubmitButton = new javax.swing.JButton();
        DrugNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DrugQuantityTextField = new javax.swing.JTextField();
        enterpriseLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        workRequestJTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        workRequestJTable.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Medicine Name", "Quantity Requested", "Sender", "Receiver", "Requested Date", "Accepted Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 150, 1360, 160);

        SubmitButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(0, 102, 102));
        SubmitButton.setText("Request Medicines");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitButton);
        SubmitButton.setBounds(100, 400, 171, 29);

        DrugNameTextField.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        DrugNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrugNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DrugNameTextField);
        DrugNameTextField.setBounds(350, 320, 160, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Medicine Name* : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 320, 127, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Quantity required* : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 360, 170, 20);

        DrugQuantityTextField.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        DrugQuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrugQuantityTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DrugQuantityTextField);
        DrugQuantityTextField.setBounds(350, 360, 160, 30);

        enterpriseLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        enterpriseLabel1.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseLabel1.setText("Request Medicines");
        jPanel1.add(enterpriseLabel1);
        enterpriseLabel1.setBounds(410, 40, 360, 50);

        backBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Back.PNG"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(12, 13, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/pharmacy.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 10, 1600, 1200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String medName = DrugNameTextField.getText();
        int medQuan;

        try{
            medQuan = Integer.parseInt(DrugQuantityTextField.getText());
            
        }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "Quantity can only be numeric");

            return;
        }
        
        if (medName.equalsIgnoreCase("") || DrugQuantityTextField.getText().equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(null, "Please enter both the mandatory fields");
        } else if (medQuan <= 0) {

            JOptionPane.showMessageDialog(null, "Quantity should be greater than 0! ");
        } else {

            PharmacyWorkRequest request = new PharmacyWorkRequest();
            request.setDrugName(medName);
            request.setDrugQuantity(medQuan);
            request.setSender(userAccount);
            request.setReceiver(null);
            request.setRequestDate(new Date());
            request.setResolveDate(null);
            request.setStatus("Requested");

            Enterprise ent = null;
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HospitalEnterprise) {
                    ent = enterprise;
                    break;
                }
            }
            if (ent != null) {
                ent.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
                //System.out.println();
            }
            //System.out.println("Testing");
            populateRequestTable();
        //System.out.println(userAccount.getWorkQueue().getWorkRequestList().get(0).toString());
            //System.out.println(userAccount.getWorkQueue().getWorkRequestList().get(1).toString());

        }
        DrugQuantityTextField.setText("");
        DrugNameTextField.setText("");
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void DrugNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrugNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrugNameTextFieldActionPerformed

    private void DrugQuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrugQuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrugQuantityTextFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DrugNameTextField;
    private javax.swing.JTextField DrugQuantityTextField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
