/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.InHomePatient.InHomePatient;
import Business.InHomePatient.InHomePatientDirectory;
import Business.Network.Network;
import Business.Role.EnterpriseAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ikyathvarmadantuluri
 */
public class NewPatientLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewPatientLoginJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;

    public NewPatientLoginJPanel(JPanel Container, EcoSystem system) {
        initComponents();
        this.userProcessContainer=Container;
        this.system=system;
        
        //populateNetworkComboBox();
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jComboBoxSex = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SignUp Screen");
        add(jLabel1);
        jLabel1.setBounds(440, 42, 276, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("UserName :");
        add(jLabel2);
        jLabel2.setBounds(350, 140, 175, 37);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Password");
        add(jLabel3);
        jLabel3.setBounds(350, 190, 175, 37);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Re-Enter Password :");
        add(jLabel4);
        jLabel4.setBounds(350, 230, 175, 37);

        txtUser.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 102, 102));
        add(txtUser);
        txtUser.setBounds(642, 146, 174, 25);

        btnCreate.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(0, 102, 102));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate);
        btnCreate.setBounds(510, 450, 130, 40);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Back.PNG"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(12, 13, 64, 58);

        txtPassword.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 102, 102));
        add(txtPassword);
        txtPassword.setBounds(640, 190, 174, 25);

        txtRePassword.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtRePassword.setForeground(new java.awt.Color(0, 102, 102));
        add(txtRePassword);
        txtRePassword.setBounds(640, 240, 174, 25);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Age of Patient :");
        add(jLabel5);
        jLabel5.setBounds(350, 280, 175, 37);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Sex :");
        add(jLabel6);
        jLabel6.setBounds(350, 330, 175, 37);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Address :");
        add(jLabel7);
        jLabel7.setBounds(350, 390, 175, 37);

        txtage.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtage.setForeground(new java.awt.Color(0, 102, 102));
        add(txtage);
        txtage.setBounds(640, 290, 174, 25);

        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 102, 102));
        add(txtAddress);
        txtAddress.setBounds(640, 390, 174, 25);

        jComboBoxSex.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jComboBoxSex.setForeground(new java.awt.Color(0, 102, 102));
        jComboBoxSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Male", "Female", "Neutral"}));
        add(jComboBoxSex);
        jComboBoxSex.setBounds(640, 340, 174, 25);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Name :");
        add(jLabel8);
        jLabel8.setBounds(350, 100, 175, 37);

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 102, 102));
        add(txtName);
        txtName.setBounds(642, 107, 174, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Health Services.png"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(0, 0, 1600, 1200);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private boolean usernamePatternCorrect() {
        Pattern pattern = Pattern.compile("(?!_).*[A-Za-z0-9._]+@[A-Za-z0-9._]+\\.[A-Za-z]{2,4}");
        Matcher matcher = pattern.matcher(txtUser.getText());

        boolean bool = matcher.matches();
        if (!bool) {
            System.out.println("Special characters are not allowed other than _, @");
            return false;
        } else {
            System.out.println("Username accepted");
            return true;
        }
    }
    
//    private void populateNetworkComboBox() {
//        networkComboBox.removeAllItems();
//
//        for (Network network : system.getNetworkList()) {
//            networkComboBox.addItem(network);
//        }
//    }
//    
//    private void populateEnterpriseComboBox(Network network) {
//        enterpriseComboBox.removeAllItems();
//
//        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
//            enterpriseComboBox.addItem(enterprise.getEnterpriseType());
//        }
//        
//
//    }
    
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
//        Enterprise enterprise = (Enterprise) enterpriseComboBox.getSelectedItem();
//        Network network = (Network) networkComboBox.getSelectedItem();
        String name = txtName.getText();
        String userName = txtUser.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String repassword = String.valueOf(txtRePassword.getPassword());
        int age;
        String sex= jComboBoxSex.getSelectedItem().toString();
        String address=txtAddress.getText();
        
        if(userName.equals("")){
            JOptionPane.showMessageDialog(null, "Username cannot be blank!");
            return;
        }
        if(password.equals("")||repassword.equals("")){
           JOptionPane.showMessageDialog(null, "Passwords cannot be blank!");
            return; 
        }
        if(!usernamePatternCorrect()){
            JOptionPane.showMessageDialog(null, "User should be of an email type and can't start with '_', '.' AND Password should be alphanumeric and can contain $,+,_ only");
            return;
        }
        if(!password.equals(repassword)){
            JOptionPane.showMessageDialog(null, "Password didnt match");
            return;
        }
        
        try{
            age = Integer.parseInt(txtage.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "please enter a valid age");
            return;
            }
        
        if(!(age<=20 || (age>=60 && age<=100))){
            JOptionPane.showMessageDialog(null, "Service are offered to patients whose age is less than 20 or  more than 60");
            return;
        }
        
        if(jComboBoxSex.getSelectedItem().toString().equalsIgnoreCase("Select")){
            JOptionPane.showMessageDialog(null, "Please select Gender");
            return;
        }
        if(txtAddress.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter address");
            return;
        }
        
        else {
            InHomePatient inHomePatient = system.getInHomePatientDirectory().createPatient(userName,name,password,age,sex,address);
            JOptionPane.showMessageDialog(null, "Patient account created successfully");
        }
        txtUser.setText("");
        txtPassword.setText("");
        txtRePassword.setText("");
        txtAddress.setText("");
//        jComboBoxSex.setSelectedItem();
        txtage.setText("");
        txtName.setText("");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> jComboBoxSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtage;
    // End of variables declaration//GEN-END:variables
}
