/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManageMainAdmin;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mounica Dantuluri
 */
public class MainAdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainAdminWorkAreaPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount account;
    public MainAdminWorkAreaPanel(JPanel userProcessContainer,EcoSystem ecosystem, UserAccount account) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.account=account;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageEnterprises = new javax.swing.JButton();
        btnManageEnterpriseAdmin = new javax.swing.JButton();
        btnManageCountries1 = new javax.swing.JButton();
        btnAnalysis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Welcome Admin");
        add(jLabel1);
        jLabel1.setBounds(509, 34, 290, 50);

        btnManageEnterprises.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnManageEnterprises.setForeground(new java.awt.Color(0, 102, 102));
        btnManageEnterprises.setText("Manage Enterprises");
        btnManageEnterprises.setPreferredSize(new java.awt.Dimension(150, 35));
        btnManageEnterprises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterprisesActionPerformed(evt);
            }
        });
        add(btnManageEnterprises);
        btnManageEnterprises.setBounds(750, 270, 300, 168);

        btnManageEnterpriseAdmin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnManageEnterpriseAdmin.setForeground(new java.awt.Color(0, 102, 102));
        btnManageEnterpriseAdmin.setText("Manage Enterprise Admin");
        btnManageEnterpriseAdmin.setPreferredSize(new java.awt.Dimension(150, 35));
        btnManageEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseAdminActionPerformed(evt);
            }
        });
        add(btnManageEnterpriseAdmin);
        btnManageEnterpriseAdmin.setBounds(290, 560, 300, 168);

        btnManageCountries1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnManageCountries1.setForeground(new java.awt.Color(0, 102, 102));
        btnManageCountries1.setText("Manage Cities");
        btnManageCountries1.setPreferredSize(new java.awt.Dimension(150, 35));
        btnManageCountries1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCountries1ActionPerformed(evt);
            }
        });
        add(btnManageCountries1);
        btnManageCountries1.setBounds(280, 270, 300, 168);

        btnAnalysis.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAnalysis.setForeground(new java.awt.Color(0, 102, 102));
        btnAnalysis.setText("Analysis");
        btnAnalysis.setPreferredSize(new java.awt.Dimension(150, 35));
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });
        add(btnAnalysis);
        btnAnalysis.setBounds(760, 550, 300, 168);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Health Services.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1600, 1190);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageEnterprisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterprisesActionPerformed
        // TODO add your handling code here:
        ManageEnterprisesJPanel manageEnterpriseJPanel=new ManageEnterprisesJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEnterprisesActionPerformed

    private void btnManageEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseAdminActionPerformed
        // TODO add your handling code here:
       ManageEnterprisesAdminJPanel manageEnterprisesAdminJPanel=new ManageEnterprisesAdminJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageEnterprisesAdminJPanel",manageEnterprisesAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnManageEnterpriseAdminActionPerformed

    private void btnManageCountries1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCountries1ActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkJPanel=new ManageNetworkJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("ManageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageCountries1ActionPerformed

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        // TODO add your handling code here:
        AnalysisJPanel analysisJPanel=new AnalysisJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("AnalysisJPanel",analysisJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnalysisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnManageCountries1;
    private javax.swing.JButton btnManageEnterpriseAdmin;
    private javax.swing.JButton btnManageEnterprises;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
