/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManageMainAdmin;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.Role.EnterpriseAdminRole;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mounica Dantuluri
 */
public class ManageEnterprisesAdminJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;


    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    public ManageEnterprisesAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateNetworkComboBox();
        
    }
        private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tableManageEnterprisesAdmin.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount;

                    model.addRow(row);
                }
            }
        }
    }
        private void populateNetworkComboBox() {
        networkComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            networkComboBox.addItem(network);
        }
    }
         private void populateEnterpriseComboBox(Network network) {
        enterpriseNameComboBox.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            enterpriseNameComboBox.addItem(enterprise);
        }

    }
    private boolean usernamePatternCorrect() {
        Pattern pattern = Pattern.compile("(?!_).*[A-Za-z0-9._]+@[A-Za-z0-9._]+\\.[A-Za-z]{2,4}");
        Matcher matcher = pattern.matcher(txtUserName.getText());

        boolean bool = matcher.matches();
        if (!bool) {
            System.out.println("Special characters are not allowed other than _, @");
            return false;
        } else {
            System.out.println("Username accepted");
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableManageEnterprisesAdmin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        enterpriseNameComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnCrerateEnterprisesAdmin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnPopulateCredentials = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Manage Enterprises Admin");
        add(jLabel1);
        jLabel1.setBounds(427, 13, 480, 50);

        tableManageEnterprisesAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "User Name"
            }
        ));
        jScrollPane1.setViewportView(tableManageEnterprisesAdmin);

        add(jScrollPane1);
        jScrollPane1.setBounds(427, 120, 454, 246);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Enterprise Name");
        add(jLabel2);
        jLabel2.setBounds(420, 400, 153, 28);

        enterpriseNameComboBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        enterpriseNameComboBox.setForeground(new java.awt.Color(0, 102, 102));
        enterpriseNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseNameComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseNameComboBox);
        enterpriseNameComboBox.setBounds(700, 400, 181, 27);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Network");
        add(jLabel3);
        jLabel3.setBounds(420, 430, 153, 28);

        networkComboBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        networkComboBox.setForeground(new java.awt.Color(0, 102, 102));
        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxActionPerformed(evt);
            }
        });
        add(networkComboBox);
        networkComboBox.setBounds(700, 440, 181, 27);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("User Name");
        add(jLabel4);
        jLabel4.setBounds(420, 470, 153, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Password");
        add(jLabel5);
        jLabel5.setBounds(420, 510, 153, 28);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Name");
        add(jLabel6);
        jLabel6.setBounds(420, 560, 153, 28);

        txtPassword.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 102, 102));
        add(txtPassword);
        txtPassword.setBounds(700, 520, 181, 28);

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 102, 102));
        add(txtName);
        txtName.setBounds(700, 560, 181, 28);

        btnCrerateEnterprisesAdmin.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnCrerateEnterprisesAdmin.setForeground(new java.awt.Color(0, 102, 102));
        btnCrerateEnterprisesAdmin.setText("Create Enterprise Admin");
        btnCrerateEnterprisesAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrerateEnterprisesAdminActionPerformed(evt);
            }
        });
        add(btnCrerateEnterprisesAdmin);
        btnCrerateEnterprisesAdmin.setBounds(560, 620, 210, 29);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Back.PNG"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(22, 13, 60, 60);

        btnPopulateCredentials.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnPopulateCredentials.setForeground(new java.awt.Color(0, 102, 102));
        btnPopulateCredentials.setText("Populate Credentials");
        btnPopulateCredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopulateCredentialsActionPerformed(evt);
            }
        });
        add(btnPopulateCredentials);
        btnPopulateCredentials.setBounds(940, 120, 190, 29);

        txtUserName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 102, 102));
        add(txtUserName);
        txtUserName.setBounds(700, 480, 181, 28);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Health Services.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 0, 1600, 1200);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
                userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MainAdminWorkAreaPanel mainAdminWorkAreaPanel = (MainAdminWorkAreaPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCrerateEnterprisesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrerateEnterprisesAdminActionPerformed
       //  TODO add your handling code here:
        Enterprise enterprise = (Enterprise) enterpriseNameComboBox.getSelectedItem();
        Network network = (Network) networkComboBox.getSelectedItem();

        String username = txtUserName.getText();
        String password = String.valueOf(txtPassword.getText());
        String name = txtName.getText();
if(username.equals("") || password.equals("") ||name.equals("") || enterprise==null || network==null){
    JOptionPane.showMessageDialog(null, "Invalid Input!");
}
else{ if (!usernamePatternCorrect()) {
            JOptionPane.showMessageDialog(null, "User should be of an email type and can't start with '_', '.' AND Password should be alphanumeric and can contain $,+,_ only");
        } else {
            Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);

            if (enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(username)) {
              // UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
           } else {
               JOptionPane.showMessageDialog(null,"Username already exist");
           }
            UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new EnterpriseAdminRole());
            populateTable();
        }}
        txtUserName.setText("");
        txtPassword.setText("");
        txtName.setText("");

    }//GEN-LAST:event_btnCrerateEnterprisesAdminActionPerformed

    private void enterpriseNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseNameComboBoxActionPerformed
        
    }//GEN-LAST:event_enterpriseNameComboBoxActionPerformed

    private void networkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxActionPerformed
        // TODO add your handling code here:
        Network network = (Network) networkComboBox.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_networkComboBoxActionPerformed

    private void btnPopulateCredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopulateCredentialsActionPerformed
        // TODO add your handling code here:
        int row = tableManageEnterprisesAdmin.getSelectedRow();
        if(row>=0){
        UserAccount userAccount = (UserAccount) tableManageEnterprisesAdmin.getValueAt(row,2);
        txtUserName.setText(userAccount.getUsername());
        txtPassword.setText(userAccount.getPassword());
        
        }
        else if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPopulateCredentialsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCrerateEnterprisesAdmin;
    private javax.swing.JButton btnPopulateCredentials;
    private javax.swing.JComboBox enterpriseNameComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JTable tableManageEnterprisesAdmin;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
