/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManageMainAdmin;

import Business.EcoSystem;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mounica Dantuluri
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;

    /**
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateNetworkTable();
    }

    private void populateNetworkTable() {
        //System.out.println("IN populate");
        DefaultTableModel model = (DefaultTableModel) tableNetwork.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableNetwork = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jCountryComboBox = new javax.swing.JComboBox();
        btnAddCity = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnDeleteCity = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(null);

        tableNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Cities"
            }
        ));
        jScrollPane1.setViewportView(tableNetwork);

        add(jScrollPane1);
        jScrollPane1.setBounds(396, 107, 350, 208);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Select City :");
        add(jLabel1);
        jLabel1.setBounds(396, 333, 122, 26);

        jCountryComboBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jCountryComboBox.setForeground(new java.awt.Color(0, 102, 102));
        jCountryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Boston", "Newyork", "Newjersey", "Texas"}));
        jCountryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCountryComboBoxActionPerformed(evt);
            }
        });
        add(jCountryComboBox);
        jCountryComboBox.setBounds(562, 335, 184, 25);

        btnAddCity.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnAddCity.setForeground(new java.awt.Color(0, 102, 102));
        btnAddCity.setText("Add City");
        btnAddCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCityActionPerformed(evt);
            }
        });
        add(btnAddCity);
        btnAddCity.setBounds(390, 400, 110, 25);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Network Management");
        add(jLabel2);
        jLabel2.setBounds(560, 10, 400, 47);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Back.PNG"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 20, 70, 60);

        btnDeleteCity.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnDeleteCity.setForeground(new java.awt.Color(0, 102, 102));
        btnDeleteCity.setText("Delete City");
        btnDeleteCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCityActionPerformed(evt);
            }
        });
        add(btnDeleteCity);
        btnDeleteCity.setBounds(590, 400, 130, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Health Services.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1600, 1200);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
                userProcessContainer.remove(this);
         Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MainAdminWorkAreaPanel mainAdminWorkAreaJPanel = (MainAdminWorkAreaPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
                                               
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCityActionPerformed
        // TODO add your handling code here:
         String name = jCountryComboBox.getSelectedItem().toString();
        Network network;
        Boolean check = true;
        //System.out.println(name);
        if(name.equalsIgnoreCase("Select")){
          JOptionPane.showMessageDialog(null, "Please select a Country");
        }
        
        else{
           if(system.getNetworkList().isEmpty()){
               
              network = system.createAndAddNetwork();
                network.setName(name);

        populateNetworkTable();
       
           }
           
           else{
            for (Network net : system.getNetworkList()) {
            
            if(name.equalsIgnoreCase(net.getName())){
            
            JOptionPane.showMessageDialog(null, "Country already exists!!");
            check = false;
             break;
        }
       
       
    }                                             
           
        if(check){
            
         network = system.createAndAddNetwork();
        network.setName(name);

        populateNetworkTable();
        //break;
            
        }}
           }
        
    }//GEN-LAST:event_btnAddCityActionPerformed

    private void btnDeleteCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCityActionPerformed
        // TODO add your handling code here:
        int row = tableNetwork.getSelectedRow();
        if(row>=0){
        Network network = (Network) tableNetwork.getValueAt(row,0);
        system.getNetworkList().remove(network);
        populateNetworkTable();
        }
        else if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDeleteCityActionPerformed

    private void jCountryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCountryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCountryComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCity;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteCity;
    private javax.swing.JComboBox jCountryComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNetwork;
    // End of variables declaration//GEN-END:variables
}
